# --- indicators metadata ---
# This script processes the raw metadata and generates a clean translation dictionary.
# It uses ASCII normalization to bypass all encoding and boundary issues.

library(dplyr)
library(stringr)

# Load existing indicators or create new
if (file.exists("data/indicators.rda")) {
  load("data/indicators.rda")
} else {
  indicators <- data.frame(M_ID = numeric(), Name_DE = character(), Unit_DE = character(), Active = logical(), stringsAsFactors = FALSE)
}

# --- Normalization Helper ---
normalize_str <- function(s) {
  # Replace common umlauts with ASCII equivalents
  s <- str_replace_all(s, "\u00e4", "ae") |> str_replace_all("\u00f6", "oe") |> str_replace_all("\u00fc", "ue")
  s <- str_replace_all(s, "\u00c4", "ae") |> str_replace_all("\u00d6", "oe") |> str_replace_all("\u00dc", "ue")
  s <- str_replace_all(s, "\u00df", "ss")
  # Handle decomposed characters (a + diaeresis)
  s <- iconv(s, to = "ASCII//TRANSLIT")
  return(s)
}

# --- Massive ASCII Translation Dictionary ---
# Keys MUST be in ASCII (as produced by normalize_str)
dict <- c(
  # Technical & Economic
  "Bruttoinlandsprodukt" = "GDP",
  "Bruttowertschoepfung" = "Gross Value Added",
  "Unternehmensdienstleistungen" = "business services",
  "Unternehmensdienstleistern" = "business service providers",
  "Unternehmensinsolvenzverfahren" = "business insolvency proceedings",
  "Unternehmensinsolvenzantrag" = "business insolvency application",
  "Verbraucherinsolvenzverfahren" = "consumer insolvency proceedings",
  "Glaeubigerforderungen" = "creditor claims",
  "Glaeubigerforderung" = "creditor claim",
  "Schuldnerquote" = "debtor rate",
  "Schuldner" = "debtors",
  "ehemals" = "formerly",
  "uebriger" = "other",
  "Investitionen" = "investments",
  "Auslandsumsatz" = "foreign turnover",
  "Umsatz" = "turnover",
  "Kaufkraft" = "purchasing power",
  "Medianeinkommen" = "median income",
  "Nettoeinkommen" = "net income",
  "Bruttoverdienst" = "gross earnings",
  "Verdienstabstand" = "earnings gap",
  "Kaufwerte" = "purchase values",
  "Einzelhandelsrelevante" = "retail-relevant",
  "einzelbetriebliche" = "individual company",
  "Wirtschaftsstruktur" = "economic structure",
  "Infrastruktur" = "infrastructure",
  "St\u00e4dtebaufoerderung" = "urban development funding",
  "Bundesfinanzhilfen" = "federal financial aid",
  "Schlüsselzuweisungen" = "key allocations",
  "Zuweisungen" = "allocations",
  "Investitionsfördermaßnahmen" = "investment funding measures",
  "Gemeinschaftsaufgabe" = "joint task",
  "Verbesserung" = "improvement",
  "Regionalförderung" = "regional funding",
  "Forschungsbauten" = "research buildings",
  "Grossgeraeten" = "large-scale equipment",
  "Hochschulpakt" = "Higher Education Pact",
  "Exzellenzinitiative" = "Excellence Initiative",
  "Programmpauschale" = "program lump sum",
  "Qualitaetspakt" = "Quality Pact",
  "Lehre" = "teaching",
  "Projektförderung" = "project funding",
  "Ressorts" = "departments",
  "Arbeitsmarktpolitische" = "labor market policy",
  "Hilfen" = "aid",
  "zivilen" = "civil",
  "zivile" = "civil",
  "ziviler" = "civil",
  "zivilem" = "civil",
  "Verarbeitendes Gewerbe" = "manufacturing sector",
  "Verarbeitenden Gewerbe" = "manufacturing sector",
  "Verarbeitende Gewerbe" = "manufacturing sector",
  "Bauhauptgewerbe" = "main construction trade",
  "Baugewerbe" = "construction industry",
  "Gewerbe" = "trade/industry",
  "Gewerbliche" = "commercial",
  "Industrie" = "industry",
  "Handwerk" = "crafts",
  "Bergbau" = "mining",
  "Primärer Sektor" = "primary sector",
  "Sekundärer Sektor" = "secondary sector",
  "Tertiärer Sektor" = "tertiary sector",
  "Primaeren" = "primary",
  "Sekundaeren" = "secondary",
  "Tertiaeren" = "tertiary",
  "Primaerer" = "primary",
  "Sekundaerer" = "secondary",
  "Tertiaerer" = "tertiary",
  "Sektor" = "sector",
  "Verarb." = "manuf.",
  "Verarb" = "manuf.",
  
  # Transport & Accessibility
  "Erreichbarkeit" = "accessibility",
  "Anschlussstelle" = "junction",
  "BAB" = "motorway",
  "Flughafen" = "airport",
  "Flughäfen" = "airports",
  "Bahnhof" = "station",
  "Bahnhoefen" = "stations",
  "Haltestelle" = "stop",
  "Haltestellen" = "stops",
  "Abfahrten" = "departures",
  "Mindestangebot" = "minimum service",
  "Werktag" = "workday",
  "Tag" = "day",
  "Fahrzeit" = "travel time",
  "Entfernung" = "distance",
  "Pkw" = "passenger cars",
  "Kraftfahrzeuge" = "motor vehicles",
  "Elektrofahrzeuge" = "electric vehicles",
  "Ladepunkte" = "charging points",
  "Strassenverkehrsunfaelle" = "road traffic accidents",
  "Verunglueckte" = "injured",
  "Getoetete" = "killed",
  
  # Tourism
  "Gaesteuebernachtungen" = "overnight stays",
  "Gaeste" = "guests",
  "Beherbergungsbetrieben" = "accommodation establishments",
  "Uebernachtungen" = "overnight stays",
  "Verweildauer" = "length of stay",
  
  # Demographics
  "Bevoelkerung" = "population",
  "Einwohnergewichtete" = "population-weighted",
  "Einwohnerdichte" = "population density",
  "Einwohner" = "inhabitants",
  "Einwohnern" = "inhabitants",
  "Inhabitantsn" = "inhabitants",
  "maennlich" = "male",
  "maennliche" = "male",
  "maennlichen" = "male",
  "weiblich" = "female",
  "weibliche" = "female",
  "weiblichen" = "female",
  "Frauen" = "women",
  "Maenner" = "men",
  "Maennern" = "men",
  "Muetter" = "mothers",
  "Muettern" = "mothers",
  "Vaeter" = "fathers",
  "Kinder" = "children",
  "Kindern" = "children",
  "Kleinkinder" = "toddlers",
  "Ganztags" = "full-day",
  "Vorschulkinder" = "preschoolers",
  "Berufsausbildung" = "vocational training",
  "Anforderungsniveau" = "requirement level",
  "Anforderungsniveaus" = "requirement levels",
  "Experte" = "expert",
  "Spezialist" = "specialist",
  "Fachkraft" = "skilled worker",
  "Helfer" = "helper",
  "offenen" = "vacant",
  "Stellen" = "vacancies",
  "Stelle" = "vacancy",
  "Schüler" = "pupils",
  "Schueler" = "pupils",
  "Schuelerinnen" = "pupils",
  "Schuelern" = "pupils",
  "Schulabgaenger" = "school leavers",
  "Schulabgaengern" = "school leavers",
  "Auszubildende" = "apprentices",
  "Auszubildenden" = "apprentices",
  "Ausbiildung" = "training",
  "Ausbildung" = "training",
  "Studierende" = "students",
  "Studierenden" = "students",
  "Hochschulen" = "universities",
  "Universitäten" = "universities",
  "Schulabschluss" = "school certificate",
  "Geborenen" = "births",
  "Geborene" = "births",
  "Geburt" = "birth",
  "Geburten" = "births",
  "Sterbefaelle" = "deaths",
  "Todesfaelle" = "deaths",
  "Gestorbene" = "deceased",
  "Eheschliessungen" = "marriages",
  "Ehescheidungen" = "divorces",
  "Einbuergerungen" = "naturalizations",
  "Auslaender" = "foreigners",
  "Auslaendern" = "foreigners",
  "Auslaendische" = "foreign",
  "Auslaendischen" = "foreign",
  "Auslaendischer" = "foreign",
  "Auslaenderinnen" = "foreign women",
  "Auslaenderanteil" = "share of foreigners",
  "Schutzsuchende" = "seekers of protection",
  "Strafrecht" = "criminal law",
  "Straftaten" = "offenses",
  "Wahlberechtigten" = "eligible voters",
  "Wahlbeteiligung" = "voter turnout",
  "Stimmenanteile" = "vote shares",
  "Zweitstimmen" = "second votes",
  "Altersgruppe" = "age group",
  "Alter" = "age",
  "Jahren" = "years",
  "Jahre" = "years",
  "Jahr" = "year",
  "laenger" = "longer",
  "aeltere" = "older",
  "aelter" = "older",
  "juengere" = "younger",
  "jaehrige" = "year-old",
  "jaehrigen" = "year-old",
  "junge" = "young",
  "alte" = "old",
  "Haushalte" = "households",
  "Haushalt" = "household",
  "Einpersonenhaushalte" = "single-person households",
  
  # Employment
  "Erwerbstaetige" = "employed people",
  "Erwerbstaetigen" = "employed",
  "Erwerbsfaehige" = "working-age population",
  "Erwerbsfaehigen" = "working-age",
  "Erwerbsfaehig" = "working-age",
  "Erwerbspersonen" = "labor force",
  "Beschaeftigte" = "employees",
  "Beschaeftigten" = "employees",
  "Beschaeftigter" = "employee",
  "Beschaeftigungsquote" = "employment rate",
  "Beschaeftigungsverhaeltnissen" = "employment relationships",
  "beschaeftigte" = "employed",
  "beschaeftigten" = "employed",
  "Sozialversicherungspflichtig" = "social security",
  "geringfuegig" = "marginal",
  "entlohnten" = "paid",
  "entlohnte" = "paid",
  "Arbeitslose" = "unemployed",
  "Arbeitslosen" = "unemployed",
  "Arbeitslosenquote" = "unemployment rate",
  "arbeitslos" = "unemployed",
  "Unterbeschaeftigte" = "underemployed",
  "Selbststaendige" = "self-employed",
  "Selbstständige" = "self-employed",
  "Selbständige" = "self-employed",
  "Vollzeit" = "full-time",
  "Teilzeit" = "part-time",
  "Vollzeitbeschäftigten" = "full-time employees",
  "Nebenjob" = "side job",
  "Minijobs" = "mini-jobs",
  "AO" = "place of work",
  "WO" = "place of residence",
  "Arbeitsplatz" = "place of work",
  "Arbeitsort" = "place of work",
  "Wohnort" = "place of residence",
  "Aufkommen" = "volume",
  "Elektrogeraete" = "electrical appliances",
  "Elektrogeraeten" = "electrical appliances",
  "Elektroaltgeräte" = "old electrical appliances",
  "Altersarmut" = "old-age poverty",
  "Grundsicherung" = "basic security",
  "Regelleistungen" = "standard benefits",
  "Asylbewerbergesetz" = "Asylum Seekers Benefits Act",
  "Asylbewerber" = "asylum seekers",
  "Leistungsberechtigte" = "eligible recipients",
  "Leistungsberechtigten" = "eligible recipients",
  "SGBII" = "SGB II",
  "SGBIII" = "SGB III",
  "XII" = "XII",
  "Insolvenzen" = "insolvencies",
  "Insolvenzverfahren" = "insolvency proceedings",
  "Schuldnerquote" = "debtor rate",
  "Arbeitsmarkt" = "labor market",
  "Arbeitsmarktpolitische" = "labor market policy",
  "Arbeitnehmern" = "employees",
  "Arbeitnehmer" = "employees",
  "Arbeitnehmerinnen" = "female employees",
  "Pendler" = "commuters",
  "Pendlern" = "commuters",
  "Einpendler" = "in-commuters",
  "Auspendler" = "out-commuters",
  "Arbeitsweg" = "commute",
  
  # Housing & Spatial
  "Wohnungen" = "dwellings",
  "Wohnung" = "dwelling",
  "Bestand" = "stock",
  "Bestandes" = "stock",
  "Neubauwohnungen" = "newly built dwellings",
  "Wohngebaeude" = "residential buildings",
  "Wohngebaeuden" = "residential buildings",
  "Nichtwohngebaeude" = "non-residential buildings",
  "Nichtwohngebaeuden" = "non-residential buildings",
  "Gebeauden" = "buildings",
  "Gebaeuden" = "buildings",
  "Haeusern" = "houses",
  "Haeuser" = "houses",
  "Einfamilienhäusern" = "single-family houses",
  "Zweifamilienh\u00e4user" = "two-family houses",
  "Zweifamilienh\u00e4usern" = "two-family houses",
  "Mehrfamilienh\u00e4user" = "multi-family houses",
  "Mehrfamilienh\u00e4usern" = "multi-family houses",
  "Einfamilienhaeuser" = "single-family houses",
  "Einfamilienhaeusern" = "single-family houses",
  "Zweifamilienhaeuser" = "two-family houses",
  "Zweifamilienhaeusern" = "two-family houses",
  "Mehrfamilienhaeuser" = "multi-family houses",
  "Mehrfamilienhaeusern" = "multi-family houses",
  "Wohnflaeche" = "living space",
  "Bodenflaeche" = "floor area",
  "Flaeche" = "area",
  "Flaechen" = "areas",
  "Umwandlungen" = "conversions",
  "Fertiggestellte" = "completed",
  "fertiggestellten" = "completed",
  "fertiggestellte" = "completed",
  "fertiggestelle" = "completed",
  "fertiggestellter" = "completed",
  "Errichtete" = "built",
  "errichteten" = "built",
  "errichtete" = "built",
  "errichteter" = "built",
  "Baugenehmigungen" = "building permits",
  "Bauueberhang" = "construction backlog",
  "Bauueberhaenge" = "construction backlog",
  "Bauland" = "building land",
  "Kaufwerte" = "purchase values",
  "m2" = "sqm",
  "sqm" = "sqm",
  "qkm" = "sqkm",
  "sqkm" = "sqkm",
  
  # Health & Social
  "Aerzte" = "physicians",
  "Arzt" = "physician",
  "Hausärzte" = "GPs",
  "Hausaerzte" = "GPs",
  "Hausarzt" = "GP",
  "Allgemeinaerzte" = "general practitioners",
  "Allgemeinärzte" = "general practitioners",
  "Kinderärzte" = "pediatricians",
  "Kinderaerzte" = "pediatricians",
  "Zahnärzte" = "dentists",
  "Zahnaerzte" = "dentists",
  "Fachaerzte" = "specialists",
  "Fachärzte" = "specialists",
  "Pflegebeduerftige" = "people in need of care",
  "Pflegebedürftige" = "people in need of care",
  "Pflege" = "care",
  "Pflegegeld" = "care allowance",
  "Pflegeheimen" = "nursing homes",
  "Pflegediensten" = "nursing services",
  "Seniorenheime" = "nursing homes",
  "Krankenhaeuser" = "hospitals",
  "Krankenhäuser" = "hospitals",
  "Notfallversorgung" = "emergency care",
  "Schlaganfallversorgung" = "stroke care",
  "Herzerkrankungen" = "heart diseases",
  "Spezialversorgung" = "specialized care",
  "Versorgung" = "care/supply",
  "Heizenergie" = "heating energy",
  "Wasserabgabe" = "water supply",
  "Letztverbraucher" = "final consumers",
  "Kleingewerbe" = "small businesses",
  "Abwasser" = "wastewater",
  "Abwassers" = "wastewater",
  "Denitrifikation" = "denitrification",
  "Phosphorelimination" = "phosphorus elimination",
  "behandelt" = "treated",
  "erneuerbarer" = "renewable",
  "naturnaehere" = "near-natural",
  "naturnähere" = "near-natural",
  
  # Education & Leisure
  "Kindertageseinrichtungen" = "childcare facilities",
  "Kindertagesstaetten" = "daycare centers",
  "Kindertagesstätten" = "daycare centers",
  "Bibliotheken" = "libraries",
  "Kinos" = "cinemas",
  "Kinosaele" = "cinema halls",
  "Baeder" = "baths/swimming pools",
  "Bäder" = "baths/swimming pools",
  
  # Administration & Finance
  "Gemeinden" = "municipalities",
  "Gemeinde" = "municipality",
  "Gemeindeverbaende" = "municipal associations",
  "Gemeindeverbände" = "municipal associations",
  "Kernhaushalt" = "core budget",
  "Steuereinnahmen" = "tax revenues",
  "Steuerkraft" = "tax capacity",
  "Kassenkredite" = "cash credits",
  "Sachinvestitionen" = "fixed asset investments",
  "Ausgaben" = "expenditure",
  "Einnahmen" = "revenue",
  "Finanzaemter" = "tax offices",
  "Polizeidienststellen" = "police stations",
  "Jobcenter" = "job centers",
  "Agenturen" = "agencies",
  "Gerichte" = "courts",
  "Amtsgerichte" = "district courts",
  "Landgerichte" = "regional courts",
  "Oberlandesgerichte" = "higher regional courts",
  
  # Environment & Environment
  "Landwirtschaftsflaeche" = "agricultural area",
  "Erholungsflaeche" = "recreational area",
  "Freiflaeche" = "open space",
  "Waldflaeche" = "forest area",
  "Wasserflaeche" = "water area",
  "Siedlungs- and traffic area" = "settlement and traffic area",
  "Verkehrsflaeche" = "traffic area",
  "Siedlungs" = "settlement",
  "Abfall" = "waste",
  "Abfaelle" = "waste",
  "Haushaltsabfaellen" = "household waste",
  "Haushaltsabfaelle" = "household waste",
  "Hausabfaelle" = "household waste",
  "Sperrmuell" = "bulky waste",
  "Wertstoffen" = "recyclables",
  "Stickstoff-Flaechenbilanz" = "nitrogen surface balance",
  "Stickstoff" = "nitrogen",
  "Ueberschuss" = "excess",
  "Trinkwasserverbrauch" = "drinking water consumption",
  
  # Migration
  "Zuzuege" = "in-migrations",
  "Fortzuege" = "out-migrations",
  "Einfamilienhaeuser" = "single-family houses",
  "Einfamilienhaeusern" = "single-family houses",
  "Zweifamilienhaeuser" = "two-family houses",
  "Zweifamilienhaeusern" = "two-family houses",
  "Mehrfamilienhaeuser" = "multi-family houses",
  "Mehrfamilienhaeusern" = "multi-family houses",
  "Wanderungssaldo" = "migration balance",
  "Zuzugsrate" = "in-migration rate",
  "Fortzugsrate" = "out-migration rate",
  "Saldo" = "balance",
  "Natuerlicher" = "natural",
  
  # Other Topics
  "Schlüsselzuweisungen" = "key allocations",
  "Bundesfinanzhilfen" = "federal financial aid",
  "Investitionsfördermaßnahmen" = "investment funding measures",
  "Staedtebaufoerderung" = "urban development funding",
  "Wirtschaftsstruktur" = "economic structure",
  "Kraftfahrzeuge" = "motor vehicles",
  "Pkw" = "passenger cars",
  "Euro" = "Euro",
  
  # Common Connectors / Small words
  "Anteil" = "share",
  "Anzahl" = "number",
  "Quote" = "rate",
  "Rate" = "rate",
  "Verhaeltnis" = "ratio",
  "Durchschnittliche" = "average",
  "Durchschnittliches" = "average",
  "Durchschnittlicher" = "average",
  "Mittel" = "average",
  "Durchschnitt" = "average",
  "mehr" = "more",
  "Gesamt" = "total",
  "gesamt" = "total",
  "insgesamt" = "total",
  "je" = "per",
  "bis" = "to",
  "unter" = "under",
  "ueber" = "over",
  "und" = "and",
  "oder" = "or",
  "u." = "and",
  "o." = "without",
  "mit" = "with",
  "ohne" = "without",
  "fuer" = "for",
  "von" = "from",
  "als" = "as",
  "den" = "the",
  "die" = "the",
  "der" = "the",
  "das" = "the",
  "dem" = "the",
  "des" = "of the",
  "im" = "in the",
  "am" = "at the",
  "in" = "in",
  "an" = "at/of",
  "zu" = "to",
  "zur" = "to the",
  "zum" = "to the",
  "alle" = "all",
  "aller" = "all",
  "allen" = "all",
  "sowie" = "as well as",
  "neu" = "new",
  "neue" = "new",
  "neuer" = "new"
)

# Normalize dictionary: everything to lower case and normalized ASCII
dict_norm <- dict
names(dict_norm) <- str_to_lower(normalize_str(names(dict)))
dict_norm <- dict_norm[!duplicated(names(dict_norm))]

# Sort by length DESC to match longer phrases first
dict_sorted <- dict_norm[order(nchar(names(dict_norm)), decreasing = TRUE)]

# Final Translation Function
translate_final <- function(txt_vec) {
  if (length(txt_vec) == 0) return(character(0))
  
  # 1. Normalize all to ASCII
  res <- normalize_str(txt_vec)
  
  # 2. Iterative replacement
  for (i in seq_along(dict_sorted)) {
    orig <- names(dict_sorted)[i]
    repl <- dict_sorted[i]
    
    # We use manual lookaround boundaries because \\b is unreliable in some R environments
    # We escape any dots in the original key for regex
    orig_esc <- str_replace_all(orig, "\\.", "\\\\.")
    pat <- paste0("(?i)(?<=^|[^a-zA-Z0-9])", orig_esc, "(?=[^a-zA-Z0-9]|$)")
    res <- str_replace_all(res, regex(pat), repl)
  }
  
  # Final Polish
  res <- str_replace_all(res, "\\[Auto-EN\\]", "")
  res <- str_replace_all(res, regex("\\bab\\b ([0-9]+)", ignore_case = TRUE), "aged $1 and older")
  # Fix common abbreviation artifacts from the tokenizer/regex
  res <- str_replace_all(res, "and\\.", "and")
  res <- str_replace_all(res, "without\\.", "without")
  res <- str_replace_all(res, "\\s+", " ")
  res <- str_trim(res)
  
  # Capitalize first letter of name
  res <- paste0(str_to_upper(str_sub(res, 1, 1)), str_sub(res, 2))
  
  return(res)
}

override_dict <- c(
  "TN23-kataster_qkm" = "Total land area sq km",
  "xbev" = "Total population",
  "xbevm" = "Male population",
  "xbevf" = "Female population",
  "bev_korr" = "Population (with BBSR census corrections)",
  "ewf_1565_ges" = "Working-age population (15 to under 65 years)",
  "et1000" = "Employed persons",
  "sva" = "Employees subject to social security contributions at the place of work",
  "svw" = "Employees subject to social security contributions at their place of residence",
  "alo" = "Unemployed",
  "GDP" = "Gross Domestic Product in 1000 Euros",
  "12" = "Percentage of unemployed persons in the civilian labor force",
  "13" = "Percentage of unemployed women in the female civilian labor force",
  "14" = "Percentage of unemployed men in the male civilian labor force",
  "15" = "Percentage of unemployed women among all unemployed",
  "16" = "Percentage of unemployed men among all unemployed",
  "17" = "Percentage of unemployed persons who have been unemployed for 1 year or longer",
  "18" = "Percentage of unemployed women who have been unemployed for 1 year or longer",
  "19" = "Percentage of male unemployed persons who have been unemployed for 1 year or longer",
  "20" = "Percentage of foreign unemployed persons among all unemployed persons",
  "21" = "Percentage of foreign female unemployed persons among all female unemployed persons",
  "22" = "Percentage of unemployed foreign men among all unemployed men",
  "23" = "Percentage of unemployed persons without vocational training",
  "24" = "Percentage of unemployed persons with expert qualification level",
  "25" = "Percentage of unemployed persons with specialist qualification level",
  "26" = "Percentage of unemployed persons with a skilled worker qualification level",
  "27" = "Percentage of unemployed persons with the required skill level of a helper",
  "28" = "Percentage of open positions requiring expert qualifications",
  "29" = "Percentage of open positions requiring specialist qualifications",
  "30" = "Percentage of job vacancies requiring a skilled worker qualification",
  "31" = "Percentage of open positions with the requirement level of helper",
  "32" = "Percentage of unemployed persons aged 55 and over in the civilian labor force aged 55 and over",
  "33" = "Percentage of unemployed persons under 25 years of age in the civilian labor force under 25 years of age",
  "34" = "Percentage of unemployed persons aged 55 and over",
  "35" = "Percentage of unemployed women aged 55 and over",
  "36" = "Percentage of unemployed men aged 55 and over",
  "37" = "Percentage of unemployed persons under 25 years of age",
  "38" = "Percentage of unemployed women under 25 years of age",
  "39" = "Percentage of unemployed men under 25 years of age",
  "40" = "Percentage of unemployed persons aged 55 and over among residents aged 55 to under 65",
  "41" = "Percentage of unemployed women aged 55 and over among female residents aged 55 to under 65",
  "42" = "Percentage of unemployed men aged 55 and over among male residents aged 55 to under 65",
  "43" = "Percentage of unemployed persons under 25 years of age among residents aged 15 to under 25",
  "44" = "Percentage of unemployed women under 25 years of age among female residents aged 15 to under 25",
  "45" = "Percentage of unemployed men under 25 years of age among male residents aged 15 to under 25",
  "46" = "Average purchase prices for building land in € per m²",
  "47" = "Building permits for new dwellings per 1,000 inhabitants",
  "48" = "Percentage of building permits for new apartments in buildings with 1 and 2 apartments",
  "49" = "Percentage of building permits for new apartments in buildings with 3 or more apartments",
  "50" = "Completed apartments per 1,000 apartments in the existing stock",
  "51" = "Percentage of newly constructed single-family and two-family houses",
  "52" = "Percentage of new dwellings in single-family and two-family houses",
  "53" = "Completed apartments in new residential buildings per 1,000 inhabitants",
  "54" = "Completed dwellings in new single-family and two-family houses per 1,000 inhabitants",
  "55" = "Completed apartments in new multi-family buildings per 1,000 inhabitants",
  "56" = "Percentage of completed residential buildings with renewable heating energy in newly constructed residential buildings",
  "57" = "Percentage of completed apartments with renewable heating energy in all constructed apartments in residential buildings",
  "58" = "Re-letting rents of advertised apartments (asking rents)",
  "59" = "Housing surplus in residential and non-residential buildings per 10,000 inhabitants",
  "60" = "Percentage of residential buildings with 1 and 2 apartments",
  "61" = "Percentage of residential buildings with 3 or more apartments",
  "62" = "Percentage of 1- and 2-room apartments",
  "63" = "Percentage of apartments with 5 or more rooms",
  "64" = "Living space per inhabitant in m²",
  "65" = "Percentage of apartments in single-family and two-family houses",
  "66" = "Percentage of apartments in multi-family buildings",
  "67" = "Social security employees at place of residence per 100 inhabitants of working age in %",
  "68" = "Social security employed women at place of residence per 100 women of working age in %",
  "69" = "Social security employed men at place of residence per 100 men of working age in %",
  "70" = "Social security employed foreigners at place of residence per 100 employable foreigners in %",
  "71" = "Ratio of young (15-<20 years) to old (60-<65 years) working-age people in %",
  "72" = "Social security employees aged 15 to under 30 years per 100 inhabitants of this age group in %",
  "73" = "Social security employees aged 55 to under 65 years per 100 inhabitants of this age group in %",
  "74" = "Percentage of employees subject to social security contributions at the place of work (part-time) out of all employees subject to social security contributions",
  "75" = "Percentage of women employed under social security at the workplace (part-time) out of all women employed under social security",
  "76" = "Labor force per 100 inhabitants of working age in %",
  "77" = "Female labor force participants per 100 women of working age in %",
  "78" = "Male labor force participants per 100 men of working age in %",
  "79" = "Self-employed persons per 100 employed persons in %",
  "80" = "Percentage of employees subject to social security contributions at the workplace with an academic vocational qualification",
  "81" = "Percentage of employees subject to social security contributions at the workplace with vocational qualifications",
  "82" = "Percentage of employees subject to social security contributions at the workplace without vocational qualifications",
  "83" = "Percentage of employees subject to social security contributions at their place of residence with an academic vocational qualification",
  "84" = "Percentage of employees subject to social security contributions at their place of residence with vocational qualifications",
  "85" = "Percentage of employees with social security contributions at their place of residence without vocational qualifications",
  "86" = "Percentage of employees subject to social security contributions at the workplace with expert qualification level",
  "87" = "Percentage of employees subject to social security contributions at the workplace with a specialist qualification level",
  "88" = "Percentage of employees subject to social security contributions at the workplace with a skilled worker qualification level",
  "89" = "Percentage of employees subject to social security contributions at the workplace with a job requirement level of helper",
  "90" = "Percentage of marginally employed workers at the workplace in private-sector employment relationships",
  "91" = "Percentage of marginally employed workers at the place of work (exclusively) in private-sector employment relationships",
  "92" = "Percentage of marginally employed persons in secondary employment at the place of work",
  "93" = "Percentage of marginally employed persons at the place of work (excluding) out of all marginally employed persons",
  "94" = "Percentage of marginally employed persons in secondary employment",
  "95" = "Percentage of marginally employed female workers among all marginally employed workers at the workplace",
  "96" = "Percentage of male employees in marginal employment",
  "97" = "Percentage of employed recipients of unemployment benefit II (ALG II) among all benefit recipients",
  "98" = "Percentage of employees on short-time work among those subject to social security contributions at the place of work",
  "99" = "Percentage of marginally employed persons aged 65 and over",
  "100" = "Percentage of male marginally employed workers aged 65 and over at the workplace",
  "101" = "Percentage of marginally employed female workers aged 65 and over",
  "102" = "Underemployed per 100 employed persons in %",
  "103" = "Percentage of employees subject to social security contributions at the workplace in the primary sector",
  "104" = "Percentage of employees subject to social security contributions at the workplace in the secondary sector",
  "105" = "Percentage of employees subject to social security contributions at the place of work in the tertiary sector",
  "106" = "Social security contributions paid at the place of work in industry per 100 inhabitants of working age in %",
  "107" = "Social security employees at the place of work in the service sector per 100 inhabitants of working age in %",
  "108" = "Percentage of employees subject to social security contributions at the workplace in knowledge-intensive business-related service sectors",
  "109" = "Percentage of employees subject to social security contributions at the workplace in creative industries",
  "110" = "Percentage of employees subject to social security contributions at the workplace in knowledge and research-intensive industries",
  "111" = "Percentage of employees subject to social security contributions in IT and scientific service occupations",
  "112" = "Percentage of employees subject to social security contributions at the workplace in craft businesses",
  "113" = "Percentage of employed persons in the primary sector",
  "114" = "Percentage of employed persons in the secondary sector",
  "115" = "Percentage of people employed in the tertiary sector",
  "116" = "Percentage of persons employed in the manufacturing sector compared to those employed in the secondary sector",
  "117" = "Share of employed persons in financial, insurance and business services as well as in real estate and housing as a percentage of employed persons in the tertiary sector",
  "118" = "Percentage of employees subject to social security contributions at the workplace in the construction industry",
  "119" = "Percentage of inhabitants under 3 years of age",
  "120" = "Percentage of residents aged 3 to under 6 years",
  "121" = "Percentage of inhabitants under 6 years of age",
  "122" = "Percentage of residents aged 6 to under 18 years",
  "123" = "Percentage of residents aged 18 to under 25",
  "124" = "Percentage of residents aged 25 to under 30",
  "125" = "Percentage of residents aged 30 to under 50",
  "126" = "Percentage of residents aged 50 to under 65",
  "127" = "Percentage of residents aged 65 to under 75",
  "128" = "Percentage of residents aged 75 to under 85",
  "129" = "Percentage of residents aged 65 and over",
  "130" = "Percentage of residents aged 75 and over",
  "131" = "Percentage of residents aged 85 and over",
  "132" = "Percentage of female residents aged 18 to under 25 years of age",
  "133" = "Percentage of female residents aged 25 to under 30 years of age",
  "134" = "Percentage of female residents aged 65 to under 75 years of age",
  "135" = "Percentage of female residents aged 75 to under 85 years of age",
  "136" = "Percentage of female residents aged 65 and over in the population of this age group",
  "137" = "Percentage of female residents aged 75 and over in the population of this age group",
  "138" = "Percentage of female residents aged 85 and over in the population of this age group",
  "139" = "Average age of the population in years",
  "140" = "Marriages per 1,000 inhabitants aged 18 and over",
  "141" = "Divorces per 1,000 inhabitants aged 18 and over",
  "142" = "Gender Index of the BBSR",
  "143" = "Percentage of foreigners among the inhabitants",
  "144" = "Percentage of female foreigners among all foreigners",
  "145" = "Persons per household",
  "146" = "Percentage of single-person households in total households",
  "147" = "Percentage of households with children in all households",
  "148" = "Population under 15 years of age per 100 inhabitants of working age",
  "149" = "Population aged 65 and over per 100 inhabitants of working age",
  "150" = "Percentage of women in the population",
  "151" = "Percentage of women in the population aged 20 to under 40",
  "152" = "Naturalizations per 1,000 foreigners",
  "153" = "Naturalizations per 1,000 inhabitants",
  "154" = "Percentage of asylum seekers in the population",
  "155" = "Percentage of asylum seekers in the foreign population",
  "156" = "Development of the number of inhabitants over the last 10 years in %",
  "157" = "Development of the number of inhabitants over the last 5 years in %",
  "158" = "Projected population development 2022 to 2030 in percent (base ROP 2045)",
  "159" = "Projected population development 2022 to 2035 in percent (base ROP 2045)",
  "160" = "Projected population development 2022 to 2040 in percent (base ROP 2045)",
  "161" = "Projected population development 2022 to 2045 in percent (base ROP 2045)",
  "162" = "Total migration balance per 1,000 inhabitants",
  "163" = "Net migration per 1,000 inhabitants",
  "164" = "Net migration of women per 1,000 female inhabitants",
  "165" = "Net migration of men per 1,000 male inhabitants",
  "166" = "Total internal migration balance per 1,000 inhabitants",
  "167" = "Net internal migration of women per 1,000 female inhabitants",
  "168" = "Net internal migration of men per 1,000 male inhabitants",
  "169" = "Net internal migration of residents aged 18 to under 25 per 1,000 residents of the age group",
  "170" = "Net internal migration of female residents aged 18 to under 25 per 1,000 female residents of that age group",
  "171" = "Net internal migration of male residents aged 18 to under 25 per 1,000 male residents of that age group",
  "172" = "Net internal migration of residents aged 25 to under 30 per 1,000 residents of the age group",
  "173" = "Net internal migration of female residents aged 25 to under 30 per 1,000 female residents of that age group",
  "174" = "Net internal migration of male residents aged 25 to under 30 per 1,000 male residents of that age group",
  "175" = "Net internal migration of residents aged 65 and over per 1,000 residents of the age group",
  "176" = "Net internal migration of inhabitants under 18 years of age per 1,000 inhabitants of the age group",
  "177" = "Net internal migration of residents aged 30 to under 50 per 1,000 residents of the age group",
  "178" = "Internal migration volume per 1,000 inhabitants",
  "179" = "Internal migration volume of women per 1,000 female inhabitants",
  "180" = "Internal migration volume of men per 1,000 male inhabitants",
  "181" = "Immigration per 1,000 inhabitants",
  "182" = "Departures per 1,000 inhabitants",
  "183" = "Immigration of women per 1,000 female inhabitants",
  "184" = "Departures of women per 1,000 female inhabitants",
  "185" = "Immigration of men per 1,000 male inhabitants",
  "186" = "Departures of men per 1,000 male inhabitants",
  "187" = "Births per 1,000 inhabitants",
  "188" = "Deaths per 1,000 inhabitants",
  "189" = "Natural balance per 1,000 inhabitants",
  "190" = "Total fertility rate (TFR)",
  "191" = "Children born to mothers aged 15 to under 20 per 1,000 women aged 15 to under 20",
  "192" = "Children born to mothers aged 40 years and over per 1,000 women aged 40 to under 45 years",
  "193" = "Proportion of deaths under 1 year of age per 1,000 inhabitants under 1 year of age",
  "194" = "Percentage of all second votes (valid and invalid) among eligible voters",
  "195" = "Percentage of second votes for CDU/CSU",
  "196" = "Percentage of second votes for the SPD",
  "197" = "Percentage of second votes cast for the Greens",
  "198" = "Percentage of second votes for the FDP",
  "199" = "Percentage of second votes for other parties",
  "200" = "Percentage of second votes for The Left Party",
  "201" = "Percentage of second votes for AfD in total second votes",
  "202" = "Crimes per 100,000 inhabitants",
  "203" = "Cases of residential burglary per 100,000 inhabitants",
  "204" = "Pupils at vocational schools per 1,000 inhabitants",
  "205" = "Percentage of female vocational school students",
  "206" = "Percentage of foreign vocational school students",
  "207" = "Total number of company-based apprenticeships per 100 applicants",
  "208" = "Trainees per 1,000 employees subject to social security contributions",
  "209" = "Percentage of female trainees",
  "210" = "Percentage of male trainees",
  "211" = "Trainees in the place of residence per 100 inhabitants aged 15 to under 25 in %",
  "212" = "Students at universities and universities of applied sciences per 1,000 inhabitants",
  "213" = "Students at universities of applied sciences per 1,000 inhabitants",
  "214" = "Percentage of female students",
  "215" = "Percentage of male students",
  "216" = "Percentage of foreign students",
  "217" = "Percentage of first-semester students",
  "218" = "Students per 100 inhabitants aged 18 to under 25 in %",
  "219" = "Pupils per 100 inhabitants",
  "220" = "Percentage of foreign students",
  "221" = "Foreign pupils per 100 foreigners aged 6 to under 18",
  "222" = "Percentage of school leavers with university entrance qualification",
  "223" = "Percentage of female school leavers with university entrance qualification",
  "224" = "Percentage of male school leavers with university entrance qualification",
  "225" = "Percentage of school leavers with a secondary school leaving certificate",
  "226" = "Percentage of female school leavers with a secondary school leaving certificate",
  "227" = "Percentage of male school leavers with a secondary school leaving certificate",
  "228" = "Percentage of school leavers with a lower secondary school leaving certificate",
  "229" = "Percentage of female school leavers with a lower secondary school leaving certificate",
  "230" = "Percentage of male school leavers with a lower secondary school leaving certificate",
  "231" = "Percentage of school leavers without a lower secondary school leaving certificate",
  "232" = "Percentage of female school leavers without a lower secondary school leaving certificate",
  "233" = "Percentage of male school leavers without a lower secondary school leaving certificate",
  "234" = "Monthly gross earnings of employees in euros",
  "235" = "Monthly gross earnings of employees in the manufacturing sector in euros",
  "236" = "Median income of full-time employees subject to social security contributions in euros",
  "237" = "Median income of female full-time employees subject to social security contributions in euros",
  "238" = "Median income of male full-time employees subject to social security contributions in euros",
  "239" = "Median income of full-time employees subject to social security contributions, aged 25 to under 55, in euros",
  "240" = "Median income of full-time employees subject to social security contributions, aged 55 to under 65, in euros",
  "241" = "Median income of full-time employees subject to social security contributions with a recognized vocational qualification in euros",
  "242" = "Median income of full-time employees subject to social security contributions with an academic degree in euros",
  "243" = "Median income of full-time employed women in relation to the median income of full-time employed men",
  "244" = "Average household income in € per inhabitant",
  "245" = "Percentage of households with a net income of less than €1,500 per month",
  "246" = "Percentage of households with a net income between €1,500 and €3,600 per month",
  "247" = "Percentage of households with a net income of over €3,600 per month",
  "248" = "Purchasing power per capita in euros",
  "249" = "Retail-relevant purchasing power per capita in euros",
  "250" = "Consumer insolvency proceedings per 1,000 inhabitants aged 18 and over",
  "251" = "Average expected creditor claims in consumer insolvency proceedings in €",
  "252" = "Percentage of formerly self-employed persons in insolvency proceedings of other debtors",
  "253" = "Private debtors per 100 inhabitants aged 18 and over in %",
  "254" = "Number of hours worked by employees",
  "255" = "Percentage of settlement and transport area in the total area",
  "256" = "Inhabitants per km² of settlement and transport area",
  "257" = "Percentage of recreational area in the total area",
  "258" = "Recreational area per inhabitant in m²",
  "259" = "Percentage of open space in the total area",
  "260" = "Open space per inhabitant in m²",
  "261" = "Percentage of agricultural land area",
  "262" = "Percentage of more natural area",
  "263" = "Area of nearer nature per inhabitant in m²",
  "264" = "Percentage of forest area",
  "265" = "Percentage of water surface area",
  "266" = "Change in settlement and transport area as a percentage of the total area compared to the previous year",
  "267" = "Amount of waste disposed of or treated per inhabitant in kg",
  "268" = "Household waste (excluding waste electrical and electronic equipment) per inhabitant in t",
  "269" = "Percentage of household and bulky waste in total household waste",
  "270" = "Percentage of organic waste in household waste",
  "271" = "Percentage of recyclable materials in household waste",
  "272" = "Nitrogen surplus of the agricultural land balance in kg N/ha FL",
  "273" = "Water supply to end consumers (households and small businesses) in liters per inhabitant per day",
  "274" = "Hospital beds per 1,000 inhabitants",
  "275" = "Doctors per 10,000 inhabitants",
  "276" = "General practitioners per 10,000 inhabitants",
  "277" = "General practitioners per 10,000 inhabitants",
  "278" = "Internists per 10,000 inhabitants",
  "279" = "Pediatricians per 10,000 children up to 15 years of age",
  "280" = "Number of people in need of care per 100 inhabitants",
  "281" = "Percentage of people receiving outpatient care compared to the total number of people requiring care",
  "282" = "Percentage of people in long-term inpatient care compared to the total number of people in need of care",
  "283" = "Percentage of recipients of care allowance among all persons in need of care",
  "284" = "Staff in nursing homes per 100 fully inpatients requiring care",
  "285" = "Staff in outpatient care services per 100 people in need of outpatient care",
  "286" = "Available places in nursing homes per 10,000 inhabitants",
  "287" = "Proportion of children under 3 years of age in daycare facilities to the children of the corresponding age group",
  "288" = "Proportion of children under 3 years of age in childcare facilities with a care time of 7 hours or more per day among the children of the corresponding age group",
  "289" = "Proportion of children aged 3 to under 6 years in daycare facilities to the children of the corresponding age group",
  "290" = "Proportion of children aged 3 to under 6 years in childcare facilities with a care time of 7 or more hours per day among the children of the corresponding age group",
  "291" = "Percentage of children of foreign origin in day care facilities",
  "292" = "Places in daycare facilities per pedagogical staff member",
  "293" = "Proportion of inclusive daycare centers among all daycare centers",
  "294" = "Municipal tax revenue in € per inhabitant",
  "295" = "Income tax in € per inhabitant",
  "296" = "Trade tax in € per inhabitant",
  "297" = "Value Added Tax in € per inhabitant",
  "298" = "Key allocations in € per inhabitant",
  "299" = "Municipal debt in € per inhabitant",
  "300" = "Cash advances in € per inhabitant",
  "301" = "Municipal staff per 10,000 inhabitants",
  "302" = "Expenditure on capital investments in € per capita",
  "303" = "Allocations for investment promotion measures in € per inhabitant",
  "304" = "Tax revenues of municipalities and municipal associations in euros per inhabitant",
  "305" = "Total planned federal financial assistance for urban development (long-term) in € per inhabitant",
  "306" = "Total federal financial aid for urban development (short-term) in € per inhabitant",
  "307" = "Approved grants for the joint task 'Improvement of the regional economic structure, individual business regional support' (long-term) in € per inhabitant",
  "308" = "Approved grants for the joint task 'Improvement of the regional economic structure, individual business regional support' (short-term) in € per inhabitant",
  "309" = "Approved grants for the joint task 'Improvement of regional economic structure infrastructure' (long-term) in € per inhabitant",
  "310" = "Approved grants for the joint task 'Improvement of regional economic structure infrastructure' (short-term) in € per inhabitant",
  "311" = "Actual federal expenditures for cooperation between the federal and state governments on research buildings and major equipment pursuant to Article 91 of the Basic Law, approvals for the Excellence Initiative and the Higher Education Pact (program allowance and Quality Pact for Teaching) (long-term) in € per capita",
  "312" = "Actual expenditures for cooperation between the federal and state governments on research buildings and major equipment pursuant to Article 91 of the Basic Law, approvals for the Excellence Initiative and the Higher Education Pact (program allowance and Quality Pact for Teaching) (short-term) in € per inhabitant",
  "313" = "Subsidies for labor market policy assistance from the Federal Employment Agency (long-term) in € per inhabitant",
  "314" = "Subsidies for labor market policy assistance from the Federal Employment Agency (short-term) in € per inhabitant",
  "315" = "Actual expenditure on direct project funding of selected departments (long-term) in € per inhabitant",
  "316" = "Actual expenditure on direct project funding of selected departments (short-term) in € per inhabitant",
  "317" = "Proportion of inhabitants in municipalities with a population density of less than 150 inhabitants/km²",
  "318" = "Population share living in medium-sized towns and potential medium-sized towns",
  "319" = "Population share living in major urban centers and potential major urban centers",
  "320" = "Inhabitants per km²",
  "321" = "Population and employees per km²",
  "322" = "Percentage of employable and non-employable benefit recipients under SGB II among the population under 65 years of age",
  "323" = "Percentage of female recipients of benefits under SGB II of all SGB II recipients",
  "324" = "Proportion of households receiving housing benefit per 1,000 households",
  "325" = "Percentage of households receiving rent subsidies per household receiving housing benefit",
  "326" = "Percentage of households receiving housing allowance",
  "327" = "Percentage of the population receiving basic income support in old age",
  "328" = "Percentage of female recipients of basic income support for the elderly in relation to the total number of recipients of basic income support for the elderly",
  "329" = "Percentage of male recipients of basic income support for the elderly in relation to the total number of recipients of basic income support for the elderly",
  "330" = "Recipients of standard benefits under the Asylum Seekers Act per 1,000 inhabitants",
  "331" = "Percentage of the population receiving social security benefits",
  "332" = "Parental allowance recipients (fathers) per 100 children under 1 year of age",
  "333" = "Percentage of fathers receiving parental allowance",
  "334" = "Percentage of mothers receiving parental allowance",
  "335" = "Percentage of single-person households receiving benefits",
  "336" = "Percentage of households with 5 or more persons in total households receiving benefits",
  "337" = "Percentage of households with children in need of assistance",
  "338" = "Persons in households receiving social assistance per 1,000 inhabitants",
  "339" = "Percentage of employable SGB II benefit recipients in the number of persons in benefit units",
  "340" = "Percentage of female recipients of benefits under SGB II of the total number of recipients of benefits under SGB II of the total number of recipients of benefits of SGB II",
  "341" = "Percentage of employable benefit recipients under 25 years of age among employable SGB II benefit recipients",
  "342" = "Percentage of employable benefit recipients over 55 years of age among employable SGB II benefit recipients",
  "343" = "Percentage of single parents eligible for benefits under SGB II among all eligible recipients of benefits under SGB II",
  "344" = "Non-employable SGB II benefit recipients under 15 years of age per 100 inhabitants under 15 years of age",
  "345" = "Average monthly entitlement amount of unemployment benefit I (SGB III) in € per recipient",
  "346" = "Average monthly entitlement amount of unemployment benefit I (SGB III) in € per male recipient",
  "347" = "Average monthly entitlement amount of unemployment benefit I (SGB III) in € per female recipient",
  "348" = "Average monthly amount of SGB II benefits in € per household",
  "349" = "Average monthly amount of unemployment benefit II (SGB II) in € per household",
  "350" = "Percentage of unemployment benefit II in SGB II benefits",
  "351" = "Average monthly amount of benefits for accommodation (SGB II) in € per household",
  "352" = "Percentage of benefits for accommodation within SGB II benefits",
  "353" = "Average monthly amount of housing benefit in € per recipient household",
  "354" = "Average car travel time to the nearest motorway junction in minutes",
  "355" = "Average car journey time to the nearest international airport in Germany in minutes",
  "356" = "Average car travel time to the nearest IC/ICE train station in minutes",
  "357" = "Average car travel time to the nearest major urban center in minutes",
  "358" = "Average car travel time to the nearest medium-sized or major town in minutes",
  "359" = "Population-weighted distance to the nearest supermarket or discount store",
  "360" = "Percentage of residents living within 1000m of the nearest supermarket or discount store",
  "361" = "Population-weighted distance to the nearest general practitioner's office",
  "362" = "Percentage of residents living within 1000m of the nearest general practitioner's office",
  "363" = "Population-weighted distance to the nearest pharmacy",
  "364" = "Percentage of residents living within 1000m of the nearest pharmacy",
  "365" = "Population-weighted distance to the nearest primary school",
  "366" = "Percentage of residents living within 1000m of the nearest primary school",
  "367" = "Population-weighted distance to the nearest public transport stop with at least 20 departures per day",
  "368" = "Percentage of residents living within 1000m of the nearest public transport stop with at least 20 departures per day",
  "369" = "Percentage of households with wired bandwidth availability of at least 50 Mbit/s",
  "370" = "Percentage of households with wired bandwidth availability of at least 100 Mbit/s",
  "371" = "Percentage of households with wired bandwidth availability of at least 1,000 Mbit/s",
  "372" = "Cars per 1,000 inhabitants",
  "373" = "Share of electric vehicles (BEVs) in the passenger car fleet in %",
  "374" = "Percentage of hybrid vehicles in the passenger car fleet",
  "375" = "Percentage of plug-in hybrid electric vehicles (PHEVs) in the passenger car fleet",
  "376" = "Percentage of petrol vehicles in the passenger car fleet",
  "377" = "Percentage of diesel vehicles in the passenger car fleet",
  "378" = "Percentage of gas-powered vehicles in the passenger car fleet",
  "379" = "Publicly accessible charging points for electric vehicles per 100,000 inhabitants",
  "380" = "Publicly accessible charging points per 100 electric vehicles (BEVs)",
  "381" = "Total road traffic accidents per 100,000 inhabitants",
  "382" = "Road traffic fatalities per 100,000 inhabitants",
  "383" = "Road traffic fatalities per 100,000 inhabitants",
  "384" = "Percentage of commuters among employees subject to social security contributions at the place of work",
  "385" = "Percentage of commuters among employees subject to social security contributions at their place of residence",
  "386" = "Commuter balance per 100 employees subject to social security contributions at the place of work",
  "390" = "Sleeping accommodations in accommodation establishments per 1,000 inhabitants",
  "391" = "Overnight stays in accommodation establishments per inhabitant",
  "392" = "Percentage of overnight stays by foreign guests",
  "393" = "Average number of overnight stays in accommodation establishments",
  "394" = "Percentage of branches with fewer than 10 employees subject to social security contributions",
  "395" = "Percentage of branches with 10 to under 50 employees subject to social security contributions",
  "396" = "Percentage of branches with 50 to under 250 employees subject to social security contributions",
  "397" = "Percentage of branches with more than 250 employees subject to social security contributions",
  "398" = "Gross domestic product in €1,000 per capita",
  "399" = "Gross domestic product in €1,000 per employed person",
  "400" = "Total gross value added in €1,000 per employed person",
  "401" = "Gross value added in the primary sector in €1,000 per employed person in the primary sector",
  "402" = "Gross value added in the secondary sector in €1,000 per employed person in the secondary sector",
  "403" = "Gross value added in the tertiary sector in €1,000 per employed person in the tertiary sector",
  "404" = "Share of gross value added in the primary sector in gross value added in %",
  "405" = "Share of gross value added in the secondary sector in gross value added in %",
  "406" = "Share of gross value added in the tertiary sector in gross value added in %",
  "407" = "Applications for corporate insolvency proceedings per 1,000 businesses",
  "408" = "Average expected creditor claim per corporate insolvency application in euros",
  "409" = "Investments in mining and manufacturing in €1,000 per employed person",
  "410" = "Foreign sales in mining and manufacturing in €1,000 per person employed",
  "411" = "Turnover in mining and manufacturing in €1,000 per person employed",
  "412" = "Turnover in the main construction industry in €1,000 per person employed in the main construction industry",
  "413" = "Turnover in the skilled trades in 1,000 euros per person employed",
  "420" = "Total number of inhabitants",
  "421" = "Cadastral area in km²",
  "422" = "Inhabitants per km²",
  "423" = "Development of the number of inhabitants over the last 5 years in %",
  "424" = "Percentage of settlement and transport area in the total area",
  "425" = "Inhabitants per km² of settlement and transport area",
  "426" = "Number of municipal or municipal association administrations",
  "427" = "Number of district administrations",
  "428" = "Number of tax offices",
  "429" = "Number of police stations",
  "430" = "Number of police stations that are not continuously available every day, but are only staffed for a few hours at a time",
  "431" = "Number of police stations that are staffed and reachable by police officers around the clock",
  "432" = "Number of employment agency administrations",
  "433" = "Number of job centers",
  "434" = "Number of employment offices and agencies",
  "435" = "Other Labour Market Administration Institutions",
  "436" = "Number of dishes",
  "437" = "Number of local courts",
  "438" = "Number of branch offices of local courts",
  "439" = "Number of regional courts",
  "440" = "Number of branch offices of regional courts",
  "441" = "Number of Higher Regional Courts",
  "442" = "Number of branch offices of Higher Regional Courts",
  "443" = "Number of employees at the workplace",
  "444" = "Number of employees at place of residence",
  "445" = "Employees at the workplace per 1000 inhabitants",
  "446" = "Employees living in the place of residence per 1000 inhabitants",
  "447" = "Number of commuters",
  "448" = "Number of commuters",
  "449" = "Number of internal commuters",
  "450" = "Commuter balance per 100 employees subject to social security contributions at the place of work",
  "451" = "Ratio of employees subject to social security contributions at the place of work to employees subject to social security contributions at their place of residence",
  "452" = "Unemployment rate measured against the working-age population",
  "453" = "Number of public transport stops",
  "454" = "Number of train stops",
  "455" = "Number of bus stops",
  "456" = "Number of subway/tram stops",
  "457" = "Number of public transport stops with a minimum service of 28 departures on a weekday",
  "458" = "Number of railway stations with a minimum service of 28 departures on a weekday",
  "459" = "Number of bus stops with a minimum service of 28 departures on a weekday",
  "460" = "Number of subway and tram stops with a minimum service of 28 departures on a weekday",
  "461" = "Number of departures from public transport stops on a weekday",
  "462" = "Number of train departures on a weekday",
  "463" = "Number of bus departures on a weekday",
  "464" = "Number of departures in subway and tram services on a weekday",
  "465" = "Average car travel time to the nearest IC/ICE train station in minutes",
  "466" = "Average car travel time to the nearest motorway junction in minutes",
  "467" = "Average car journey time to the nearest international airport in Germany in minutes",
  "468" = "Truck travel time to the nearest combined transport terminal in minutes",
  "469" = "Car travel time to the nearest medium-sized or major city in minutes",
  "470" = "Car travel time to the nearest major urban center in minutes",
  "471" = "Percentage of households with wired bandwidth availability of at least 50 Mbit/s",
  "472" = "Percentage of households with wired bandwidth availability of at least 100 Mbit/s",
  "473" = "Percentage of households with wired bandwidth availability of at least 1,000 Mbit/s",
  "474" = "Number of post offices of Deutsche Post AG",
  "475" = "Number of postal agencies of Deutsche Post AG in retail stores",
  "476" = "Total number of post offices of Deutsche Post AG",
  "477" = "Number of hospitals",
  "478" = "Number of hospitals not participating in 'General inpatient emergency care' (Level 0)",
  "479" = "Number of hospitals participating in 'General Inpatient Emergency Care' and providing basic emergency care (Level 1)",
  "480" = "Number of hospitals participating in 'General Inpatient Emergency Care' and meeting the Extended Emergency Care (Level 2) requirements",
  "481" = "Number of hospitals participating in 'General Inpatient Emergency Care' and meeting Comprehensive Emergency Care (Level 3)",
  "482" = "Number of hospitals participating in the 'Special Inpatient Emergency Care' program and providing care for severely injured patients (Module 1)",
  "483" = "Number of hospitals participating in the 'Special Inpatient Emergency Care' program and providing emergency care for children (Module 2)",
  "484" = "Number of hospitals participating in the 'Special Inpatient Emergency Care' program and fulfilling the special care requirements (Module 3)",
  "485" = "Number of hospitals participating in the 'Special Inpatient Emergency Care' program and fulfilling stroke care requirements (Module 4)",
  "486" = "Number of hospitals participating in the 'Special Inpatient Emergency Care' program and providing care for acute heart conditions (Module 5)",
  "487" = "Number of hospital beds",
  "488" = "Hospital beds per 1,000 inhabitants",
  "489" = "Percentage of residents living within 1000m of the nearest pharmacy",
  "490" = "Doctors per 10,000 inhabitants",
  "491" = "Population per doctor",
  "492" = "General practitioners per 10,000 inhabitants",
  "493" = "General practitioners per 10,000 inhabitants",
  "494" = "Internists per 10,000 inhabitants",
  "495" = "Pediatricians per 10,000 children up to 15 years of age",
  "496" = "Number of pharmacies",
  "497" = "Number of retirement homes",
  "498" = "Number of universities and colleges",
  "499" = "Number of students at universities and colleges",
  "500" = "Students at universities and colleges per 1,000 inhabitants",
  "501" = "Students at universities of applied sciences per 1,000 inhabitants",
  "502" = "Number of primary schools",
  "503" = "Number of pupils in primary schools",
  "504" = "Pupils in primary schools per 1,000 inhabitants",
  "505" = "Number of general education schools",
  "506" = "Number of pupils in general education schools",
  "507" = "Pupils in general education schools per 1,000 inhabitants",
  "508" = "Number of secondary schools",
  "509" = "Number of pupils in secondary schools",
  "510" = "Pupils in secondary schools per 1,000 inhabitants",
  "511" = "General education schools with a focus on special needs",
  "512" = "Pupils at general education schools with a focus on special needs",
  "513" = "Pupils at general education schools with a focus on special needs per 1,000 inhabitants",
  "514" = "Number of vocational schools",
  "515" = "Number of pupils in vocational schools",
  "516" = "Pupils in vocational schools per 1,000 inhabitants",
  "517" = "Number of libraries",
  "518" = "Number of public libraries",
  "519" = "Number of scientific libraries",
  "520" = "Number of special libraries",
  "521" = "Number of physical media loans",
  "522" = "Number of cinemas",
  "523" = "Number of cinemas",
  "524" = "Number of cinema seats",
  "525" = "Number of public baths",
  "526" = "Number of non-public baths",
  "527" = "Total number of bathrooms",
  "528" = "Number of daycare centers",
  "529" = "Proportion of those entitled to benefits under SGB II or SGB XII",
  "530" = "Non-employable SGB II benefit recipients under 15 years of age per 100 inhabitants under 15 years of age",
  "531" = "Percentage of the population receiving basic income support in old age",
  "532" = "Excess of the nitrogen balance of the agriculturally used area in kg N /ha LN",
  "533" = "Deaths of people aged under 70 per 1,000 inhabitants aged under 70",
  "534" = "Population-weighted distance to the nearest general practitioner",
  "535" = "Population-weighted distance to the nearest pharmacy",
  "536" = "Staff in outpatient care services per person in need of care",
  "537" = "Number of available inpatient places in nursing homes per 1,000 inhabitants aged 65 and over",
  "538" = "Population-weighted distance to the nearest primary school",
  "539" = "Percentage of school leavers without a lower secondary school leaving certificate",
  "540" = "Proportion of children under 3 years of age in daycare facilities to the children of the corresponding age group",
  "541" = "Proportion of inclusive daycare centers among all daycare centers",
  "542" = "Ratio of the employment rate of women to the employment rate of men",
  "543" = "Number of women with mandates in city councils and district councils as a percentage of all mandates",
  "544" = "Percentage of wastewater treated by denitrification and phosphorus removal in total wastewater",
  "545" = "Publicly accessible charging points for electric vehicles per 1,000 inhabitants",
  "546" = "Gross domestic product in € per capita",
  "547" = "Percentage of long-term unemployed persons in the total labor force",
  "548" = "Social security employees at place of residence per 100 inhabitants of working age in %",
  "549" = "Social security employees aged over 55 years at their place of residence per 100 inhabitants of this age group in %",
  "550" = "Percentage of employed recipients of unemployment benefit II (ALG II) among all benefit recipients",
  "551" = "New commercial establishments per 1,000 inhabitants",
  "552" = "Social security employees at the workplace with an academic vocational qualification as a percentage of social security employees",
  "553" = "Percentage of households with wired bandwidth availability of at least 100 Mbit/s",
  "554" = "Ratio of the employment rate of foreign nationals to the total employment rate",
  "555" = "Number of naturalized persons as a percentage of residents with foreign citizenship",
  "556" = "Re-letting rents of advertised apartments (asking rents)",
  "557" = "Living space per inhabitant in m²",
  "558" = "Population-weighted distance to the nearest supermarket/discount store",
  "559" = "Number of cars per 1,000 inhabitants",
  "560" = "Share of electric vehicles (BEVs) in the passenger car fleet in %",
  "561" = "Road traffic fatalities per 1,000 inhabitants",
  "562" = "Percentage of settlement and transport area in the total area",
  "563" = "Change in settlement and transport area as a percentage of the total area compared to the previous year",
  "564" = "Settlement and transport area per inhabitant in m²",
  "565" = "Recreational area in m² per inhabitant",
  "566" = "Percentage of completed residential buildings with renewable heating energy in all residential buildings",
  "567" = "Water supply to end consumers (households and small businesses) in liters per inhabitant per day",
  "568" = "Generation of household waste (excluding electrical appliances) per capita in t",
  "569" = "Crimes per 1,000 inhabitants",
  "570" = "Tax revenues of municipalities and municipal associations in euros per inhabitant",
  "571" = "Cash advances in the core budget per capita"
)

# --- Apply Translation & Overrides ---

# 1. General Translation Engine
indicators <- indicators |>
  mutate(Name_EN = translate_final(Name_DE))

# 2. Apply User Overrides (Match by ID column)
for (id_key in names(override_dict)) {
  if (id_key %in% indicators$ID) {
    indicators$Name_EN[indicators$ID == id_key] <- override_dict[id_key]
  }
}

# --- Check for failures ---
ads <- indicators$Name_EN[indicators$Active]
bad <- ads[grepl("[^ -~]", ads)] # Non-ASCII check
if (length(bad) > 0) {
  message("WARNING: Some non-ASCII characters remain.")
}

# --- Save Data ---
usethis::use_data(indicators, overwrite = TRUE)
message("Processed ", nrow(indicators), " indicators with string-ID overrides.")
