# This script processes the raw metadata file into an .rda file for the package
# Run this manually when the source Excel file changes.

library(readxl)
library(dplyr)
library(usethis)


# Read German Data
raw_de <- readxl::read_excel(
  "Uebersicht der Indikatoren DE.xlsx",
  sheet = "Raumbeobachtung DE",
  skip = 1
)

# Read English Data
raw_en <- readxl::read_excel(
  "Uebersicht der Indikatoren EN.xlsx",
  sheet = " Spatial observation EN",
  skip = 1
)

# Process DE (Primary)
df_de <- raw_de |>
  dplyr::rename(
    ID = any_of(c("Kürzel", "Code")),
    Name_DE = any_of(c("Kurzname", "Indikator")),
    Description_DE = any_of(c("Name", "Beschreibung")),
    Theme = any_of(c("Bereich", "Theme"))
  ) |>
  dplyr::filter(!is.na(ID), !is.na(Name_DE))

# Process EN (Lookup)
df_en <- raw_en |>
  dplyr::select(
    M_ID,
    Name_EN = name, # Extract English Name
    Anmerkungen_EN = Notes,
    Stat_Grund_EN = `Statistical principles`
  ) |>
  dplyr::filter(!is.na(M_ID))

# Join and Finalize
indicators <- df_de |>
  dplyr::left_join(df_en, by = "M_ID") |>
  dplyr::mutate(
    # Fallback if specific EN name missing
    Name_EN = ifelse(is.na(Name_EN), paste(Name_DE, "(EN)"), Name_EN),
    Theme = if ("Theme" %in% names(df_de)) Theme else NA_character_,
    Unit_DE = NA_character_,
    Unit_EN = NA_character_
  ) |>
  dplyr::select(
    ID,
    Name_DE,
    Name_EN,
    Description_DE,
    Theme,
    dplyr::everything()
  )

# Save to
# --- 5. Enrich with API Activity Status ---
# Read the catalog generated by scan_api.R if it exists
# --- 5. Enrich with API Activity Status ---
# Read the catalog generated by scan_api.R if it exists
status_file <- "data-raw/api_catalog.csv"
if (file.exists(status_file)) {
    message("Merging active status from api_catalog.csv...")
    api_status <- read.csv(status_file, stringsAsFactors = FALSE)
    
    # "ID" in csv is the M_ID
    # We want to add an "Active" column (TRUE/FALSE)
    # Default is FALSE
    indicators$Active <- FALSE
    
    # 1. Update existing matches
    # api_status$ID corresponds to indicators$M_ID
    existing_matches <- which(indicators$M_ID %in% api_status$ID[api_status$Active == TRUE])
    indicators$Active[existing_matches] <- TRUE
    
    # 2. Append NEW active indicators not in current metadata
    # Identify IDs in api_status that are active BUT NOT in indicators$M_ID
    active_api <- subset(api_status, Active == TRUE)
    new_ids <- setdiff(active_api$ID, indicators$M_ID)
    
    if (length(new_ids) > 0) {
        message("Appending ", length(new_ids), " new active indicators from API scan...")
        
        new_rows <- data.frame(
            ID = as.character(new_ids), # Use M_ID as string ID for consistency
            Name_DE = active_api$Name[match(new_ids, active_api$ID)],
            Name_EN = {
                # Heuristic Translation for Discovered Indicators
                vals <- active_api$Name[match(new_ids, active_api$ID)]
                
                # Basic replacements
                vals <- gsub("Anteil der", "Share of", vals)
                vals <- gsub("Zahl der", "Number of", vals)
                vals <- gsub("insgesamt", "Total", vals)
                vals <- gsub("Einwohner", "Inhabitants", vals)
                vals <- gsub("Bevölkerung", "Population", vals)
                vals <- gsub("Erwerbstätigen", "Employed", vals)
                vals <- gsub("Erwerbspersonen", "Labor Force", vals)
                vals <- gsub("Arbeitslosen", "Unemployed", vals)
                vals <- gsub("Arbeitslose", "Unemployed", vals)
                vals <- gsub("Frauen", "Women", vals)
                vals <- gsub("Männer", "Men", vals)
                vals <- gsub("weiblichen", "Female", vals)
                vals <- gsub("männlichen", "Male", vals)
                vals <- gsub("weibliche", "Female", vals)
                vals <- gsub("männliche", "Male", vals)
                vals <- gsub("Jugendliche", "Youth", vals)
                vals <- gsub("unter", "under", vals)
                vals <- gsub("Jahren", "years", vals)
                vals <- gsub("Jahre", "years", vals)
                vals <- gsub("bis", "to", vals)
                vals <- gsub("und älter", "and older", vals)
                vals <- gsub("Ausländer", "Foreigners", vals)
                vals <- gsub("Wanderungssaldo", "Migration Balance", vals)
                vals <- gsub("Geborene", "Births", vals)
                vals <- gsub("Gestorbene", "Deaths", vals)
                vals <- gsub("Haushalte", "Households", vals)
                vals <- gsub("Bodenfläche", "Land Area", vals)
                vals <- gsub("Siedlungs- und Verkehrsfläche", "Settlement and Transport Area", vals)
                vals <- gsub("Bruttoinlandsprodukt", "GDP", vals)
                vals <- gsub("Verfügbares Einkommen", "Disposable Income", vals)
                vals <- gsub("je 1000", "per 1,000", vals)
                vals <- gsub("je 100", "per 100", vals)
                vals <- gsub("je", "per", vals)
                
                # Suffix
                paste(vals, "[Auto-EN]") 
            },

            Description_DE = NA_character_,
            Theme = "API Discovered",
            Algorithmus = NA_character_,
            M_ID = as.numeric(new_ids),
            Anmerkungen = "Discovered via API Scan",
            Statistische_Grundlagen = NA_character_,
            Gemeinden = "Unknown",
            Kreise = "Active",
            Anmerkungen_EN = NA_character_,
            Stat_Grund_EN = NA_character_,
            Unit_DE = NA_character_,
            Unit_EN = NA_character_,
            Active = TRUE,
            stringsAsFactors = FALSE
        )
        
        # Rename 'Statistische_Grundlagen' to match column name in indicators if needed
        # indicators usually has "Statistische Grundlagen" (space) or underscore?
        # Let's check colnames of indicators before binding
        # The script creates 'Statistische Grundlagen' (space) in earlier steps?
        # Ah, look at line 48: select(..., `Statistische Grundlagen` = ...)
        # So the column name has a space.
        
        names(new_rows)[names(new_rows) == "Statistische_Grundlagen"] <- "Statistische Grundlagen"
        
        # DEBUG: Check structures
        message("Structure of existing indicators:")
        str(indicators)
        message("Structure of new rows:")
        str(new_rows)
        
        # Bind
        indicators <- dplyr::bind_rows(indicators, new_rows)
    }
    
    message("Binding successful. Total indicators now: ", nrow(indicators))
    message("Total active: ", sum(indicators$Active, na.rm=TRUE))
} else {
    warning("api_catalog.csv not found. Active column will be NA.")
    indicators$Active <- NA
}

# --- 6. Saving ---
usethis::use_data(indicators, overwrite = TRUE)

message("Processed ", nrow(indicators), " indicators.")
